name: ci

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # required for OIDC

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Auth to GCP via OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_CI_SA_EMAIL }}

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build & Push Image
        id: image
        run: |
          IMAGE="${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/app-images/ingest:latest"
          docker build -t "$IMAGE" ./app
          docker push "$IMAGE"
          echo "image_ref=$IMAGE" >> $GITHUB_OUTPUT

      - name: Terraform Init/Plan/Apply
        working-directory: infra
        env:
          TF_VAR_project_id: ${{ vars.GCP_PROJECT }}
          TF_VAR_region: ${{ vars.GCP_REGION }}
          TF_VAR_bq_location: US
          TF_VAR_image_ref: ${{ steps.image.outputs.image_ref }}
          TF_VAR_source_url: https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist.csv
        run: |
          terraform init
          terraform fmt -check
          terraform validate
          terraform plan -out tfplan
          terraform apply -auto-approve tfplan